defaults:
  - ../../../../configs/defaults/base_training.yaml
  - ../dataset.yaml
  - ../sensors/u_only_random_variable.yaml
  - ../../../../configs/models/senseiver.yaml
case: brusselator
optimization: {batch_size: 4}
runtime: {num_workers: 4, data_strategy: auto}
output: {experiment_name: senseiver_plain}
